name: Entrega para ECS

on:
  workflow_call:

jobs:

  ecs:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: sa-east-1
        
    - name: Get task file
      run: aws ecs describe-task-definition --task-definition Tarefa_API_GO:3 --query taskDefinition > task-definition.json
    
    - uses: actions/checkout@v3
    
